### ISSUE TITLE
🎨 マルチテーマシステム実装 - 青空・夕焼け・カスタムテーマ対応

### ISSUE THREAD

**Issue by rmc8** [rmc8/moodeSky#10]
## 📋 概要

moodeSkyに現代的で柔軟なマルチテーマシステムを実装し、**青空をイメージしたライトテーマ**、**夕焼けをイメージしたダークテーマ**、**日本の伝統色カスタムテーマ**を提供します。TailwindCSS v4の最新機能とSvelte 5 runesを活用した効率的なテーマ切り替えシステムを構築します。

### 基本テーマ (3つのモード)
1. **🌤️ ライトテーマ**: 青空をイメージした青色アクセント（実用性重視）
2. **🌅 ダークテーマ**: 夕焼けをイメージした橙色アクセント
3. **⚙️ システムテーマ**: OS設定に応じてライト or ダーク自動選択

### カスタムテーマ (ユーザー選択)
- **プリセット集**から選択可能
- 各プリセットにライト・ダーク両方のバリエーション
- 初期実装: 日本の伝統色プリセット

---

#### 🏗 アーキテクチャ基盤 (100% 完了)
- [x] **TailwindCSS v4統一アーキテクチャ**: data-theme属性による統一的なテーマ制御
- [x] **@layer base + @theme inline構成**: 現代的なCSS変数システム
- [x] **レガシーdark:プレフィックス完全移行**: 保守性向上
- [x] **Tauri Store Plugin統合**: テーマ設定の永続化とセキュア保存
- [x] **Svelte 5 runes対応**: リアクティブテーマ管理

#### 🎨 基本テーマシステム (100% 完了)
- [x] **Sky テーマ (青空ライト)**: 青色アクセント・実用性重視デザイン
- [x] **Sunset テーマ (夕焼けダーク)**: 橙色アクセント・美的ダークテーマ
- [x] **ハイコントラストテーマ**: アクセシビリティ対応
- [x] **システム連動**: OS設定に応じた自動テーマ選択

#### 👁 視認性・アクセシビリティ (100% 完了)
- [x] **WCAG AAA基準達成**: Sunsetテーマでコントラスト比7:1以上
- [x] **科学的根拠に基づく最適化**: 相対輝度計算による文字色最適化
- [x] **統一クラス体系**: `.text-themed`, `.bg-themed`, `.text-label`等
- [x] **全ページ対応**: ログイン・デッキ・コンポーネント完全移行

#### 🛠 技術実装 (100% 完了)
- [x] **CSS変数システム**: RGB空間分離値によるテーマトークン
- [x] **ThemeToggleコンポーネント**: 3テーマ切り替えUI
- [x] **リアルタイム切り替え**: スムーズなアニメーション対応
- [x] **型安全なテーマ管理**: TypeScript完全対応

#### 🌈 カスタムテーマシステム
- [ ] **日本の伝統色プリセット**: 藍・朱・桜・抹茶色ベースのテーマ
- [ ] **カスタムテーマエディター**: HSL/OKLCH色空間対応のカラーピッカー
- [ ] **プリセット管理**: 保存・読み込み・削除機能
- [ ] **コミュニティテーマ**: インポート・エクスポート機能

#### 🔧 高度な設定
- [ ] **アクセシビリティ拡張**: より詳細な色覚サポート
- [ ] **フォントサイズカスタマイズ**: テーマごとの文字サイズ調整
- [ ] **アニメーション設定**: テーマ切り替えエフェクトのカスタマイズ

---

### CSS変数システム (実装済み)
```css
@layer base {
  @theme {
    /* Sky テーマ (ライト) */
    --color-primary: 14 165 233;      /* sky-500 */
    --color-surface: 248 250 252;     /* slate-50 */
    --color-foreground: 15 23 42;     /* slate-900 */
    
    /* Sunset テーマ (ダーク) */
    --color-muted: 226 232 240;       /* slate-200 - 視認性最適化 */
  }
  
  /* 統一クラス体系 */
  .bg-themed { background-color: rgb(var(--color-background)); }
  .text-themed { color: rgb(var(--color-foreground)); }
  .text-label { color: rgb(var(--color-foreground)); opacity: 0.85; }
  .button-primary { background: var(--color-primary); color: var(--color-background); }
}
```

### data-theme属性システム (実装済み)
```html
<html data-theme="sky">      <!-- ライトテーマ -->
<html data-theme="sunset">   <!-- ダークテーマ -->  
<html data-theme="high-contrast"> <!-- ハイコントラスト -->
```

### ThemeToggle コンポーネント (実装済み)
- 3テーマ切り替えドロップダウンUI
- アイコン付きオプション表示
- Tauri Store Plugin による設定永続化
- システムテーマ自動検出・切り替え

### ✅ 完全達成済み
- **ユーザー体験**: 特にSunsetテーマで大幅な視認性向上
- **技術的価値**: TailwindCSS v4ベストプラクティス実装
- **保守性**: 統一されたクラス体系による開発効率化
- **アクセシビリティ**: WCAG AAA基準達成

### 🎯 プロダクト差別化達成
- ✅ **空・夕焼けコンセプト**: 他Blueskyクライアントにない詩的テーマ
- ✅ **統一アーキテクチャ**: data-theme属性による現代的実装
- ✅ **視認性重視**: 科学的根拠に基づく色彩最適化

### 短期 (現状で十分)
現在実装されている**Sky/Sunset/ハイコントラスト**の3テーマで、基本的なテーマシステムとしては完成度が高く、プロダクトとして十分使用可能。

### 中長期 (必要に応じて)
- 日本の伝統色プリセット追加
- カスタムテーマエディター実装
- コミュニティテーマ機能

---

### 実装済み参考事例
- **PR #11**: Sky & Sunset テーマシステム実装
- **PR #12**: 視認性向上とアーキテクチャ統一  
- **PR #13**: 設定ファイル整理とレイアウト最適化

### TailwindCSS v4
- [Theme variables - TailwindCSS v4](https://tailwindcss.com/docs/theme)
- [Multi-Theme Strategy - simonswiss](https://simonswiss.com/posts/tailwind-v4-multi-theme)

### SvelteKit統合
- [Dark Mode with SvelteKit - dev.to](https://dev.to/willkre/persistent-theme-switch-dark-mode-with-svelte-sveltekit-tailwind-1b9g)
- [Svelte 5 Runes Documentation](https://svelte.dev/docs/runes)

---

**現状**: マルチテーマシステムの**基盤と主要機能は完全実装済み**。残りのカスタムテーマ機能は将来の拡張として位置づけ、現在のシステムでもプロダクトとして十分な完成度を達成。
